name: Release Helm chart

on:
  push:
    tags:
      - 'onyx-stack-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: deployment/helm/charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
